apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.4.2/deploy/longhorn.yaml
  - ingress.http.yaml
  - ingress.https.yaml
  - middleware.redirect-to-https.yaml
  - recurring-job.arr-config.yaml
  - sealed-secret.backup.yaml
  - setting.backup.yaml
  - nodes/
