apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.4.2/deploy/longhorn.yaml
  - backup-target.yaml
  - ingress.http.yaml
  - ingress.https.yaml
  - middleware.redirect-to-https.yaml
  - sealed-secret.backup.yaml
  - nodes/
