apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target
value: s3://betelgeuse-longhorn-backup@us-east-005/
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target-credential-secret
value: backblaze-credentials
