apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target
value: s3://betelgeuse@sgp1/
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target-credential-secret
value: do-credentials
