apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
commonLabels:
  app: prowlarr
resources:
  - config-map.yaml
  - deployment.yaml
  - ingress.http.yaml
  - ingress.https.yaml
  - middleware.redirect-to-https.yaml
  - persistent-volume-claim.yaml
  - service.yaml
