apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
spec:
  selector:
    matchLabels:
      app: vaultwarden
  replicas: 1
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:1.28.1-alpine
          env:
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vaultwarden.vaultwarden-db.credentials.postgresql.acid.zalan.do
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vaultwarden.vaultwarden-db.credentials.postgresql.acid.zalan.do
                  key: password
            - name: DATABASE_URL
              value: "postgresql://$(DATABASE_USERNAME):$(DATABASE_PASSWORD)@vaultwarden-db:5432/vaultwarden"
          envFrom:
            - secretRef:
                name: admin-token
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
          - name: data
            mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vaultwarden-data
      restartPolicy: Always
