apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden-http
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: vaultwarden-redirect@kubernetescrd
  labels:
    app: vaultwarden
spec:
  rules:
    - host: vaultwarden.lan
      http:
        paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: vaultwarden
               port:
                 name: http
