apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-db
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: hactar.lan
    path: /mnt/tank/server/vaultwarden/db
