apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: vaultwarden-db
spec:
  teamId: vaultwarden
  numberOfInstances: 1
  volume:
    storageClass: nfs
    size: 2Gi
  users:
    admin:
      - superuser
      - createdb
    vaultwarden: []
  databases:
    vaultwarden: vaultwarden
  postgresql:
    version: "15"
