apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: smtp-password
  namespace: vaultwarden
spec:
  encryptedData:
    SMTP_PASSWORD: AgCA7MlMlt7e8HO+xdiviYbYXZfBg97ZJubjS1YfanyHsue3vEynCRGmfBO5UyIl2w/mc7hwk44E2vPfbNWcFIxj2lRHb5yTce0VF0vwCZjq7z6F32a3h+2IZCXJdroE+d5S8sOCrl/Iz7SvAfx8QkLSTjc/MK+2MWEwGfLxEsMa1t8GVhDgp7VPm3f8Y59VDy1mWF+mJNoSelpevJoC13UfGPGwqjaQU8/P2SlxqWRUU3cwHUvjMNyURTs86PC6YizdImqEr2SwB2UPFAG3/d2WJ+DQr7+xzgddZWd8E6fj7TFn2ogt1g6JAKRcV6Uc7LLC+rvem0LAIYEEY4ZNYgT6eCqIicStd7W4Sj2a9OMzyYYoACRL9K9BpHVLuMxLTj6DR0WGkOChUt2q+QME1KW16XKmbuxTyJIzautjPftM6uRmZj/DgpGEOQk4QW955uwQauwYXrzERBcOOikf8Anz+6eTGcRva9FFPtDXPdJvm307n/4XaZayPPJ64U56sKuLvS/QdXzeFw51zgUCGr3twg21CQg0oAyet8GJuTIr1K6p4erNp0L3Jo2djOLUHKw2F3OinjOZMGy24eFRk0AuwVf5Q43Sg1k07TsgUw7gMVk0QVCviVa2UqoHzMAJ0n/iqcA6fnLAoknw8VT77ClmJaPk/C1nZQ3RyCQSrmY4dHZs2efUjtmWQI5ONpHXq5u+IISNulesdBFjRWElKKk0
  template:
    metadata:
      creationTimestamp: null
      name: smtp-password
      namespace: vaultwarden

