apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: smtp-password
  namespace: vaultwarden
spec:
  encryptedData:
    SMTP_PASSWORD: AgAFSEdn0fnK5EhIEVuSzFHAqEkiAwSqOM1tKe4V3ilbjQ1Mw0d6dXLusOsHpf0Y6+ZlivXGPQWP8ZoruVRoOXX8dcIvWOIHtooASuAdfel062Pr8y9h5LAK+L+wH3KOa7jqmhzJyKDGu6Fx0tBuqeHGkK/TQcE6e9i3SsJEqBnhWKbg2Mq/4acIBxmXwJHpeDgTwnfxqq+7YzWS7FwYJF7pPAx0akdLLg+A5JKVWJVxZf4HwimT0tid6wD0amjoZtlYuPywOEAw97sNGd28JnFiNkqJ0sShEOUmsqmc4ggJ9jih1jg0FRUldWoHVCVXeuFBs55B6hBaXMtgiPNrNaHKUZTj7P1AXRXvT9g6BUoAgi3U/2ujT75zWyAPGjGLh3RVv56iIO1ScT8OtLujh+p3IbtbFPh5CGYqh7plbt6H8bwXnATmarSaG+1qlRFxxcW/JEGqkUuVt482/ekfkiQH11B0HHgD6o+8H4WXsjKaP4cu1agJ8hBqw3J4lUP4SJSfDqK//ARZVosolSw9rXVXkghKXZm8quhCpPiPs2EJhN1gvNgDV3uZtomyINE8fsrnJlgvVAN5ydXU1j7EtergkL67mV9t/pLQI8zbMK9eAISs5yauZ7rVPF3eLvS4usnjiAiE0MNjOpoF+i+KpUgFDGkqF3ANVYXnNKfI9UKJxEPbGYfq+vaaCOx860pWhmfiCYQY2O0SxRcJqDN9W4iC
  template:
    metadata:
      creationTimestamp: null
      name: smtp-password
      namespace: vaultwarden

