apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  annotations:
    external-dns.alpha.kubernetes.io/hostname: vaultwarden.lan
  labels:
    app: vaultwarden
spec:
  selector:
    app: vaultwarden
  type: LoadBalancer
  ports:
    - name: vaultwarden
      protocol: TCP
      port: 80
      targetPort: http
