apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  replicas: 0
  template:
    spec:
      containers:
        - name: radarr
          image: linuxserver/radarr@sha256:f98f655d5d26941f19f363a0193477f2e69ed25e4c997009ee9e0de8a678f4ec
          envFrom:
            - configMapRef:
                name: arr-common-config
          ports:
            - name: http
              containerPort: 7878
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: data
          persistentVolumeClaim:
            claimName: media-data
