apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: sonarr
          image: linuxserver/sonarr@sha256:540d2b65fdbaffc2e2c7939b35dcb8fb75facf4b2e4297b54037993ce28d4a19
          envFrom:
            - configMapRef:
                name: arr-common-config
          ports:
            - name: http
              containerPort: 8989
          volumeMounts:
            - name: media
              mountPath: /config
              subPath: sonarr
            - name: media
              mountPath: /data
              subPath: library
      volumes:
        - name: media
          nfs:
            server: hactar.lan
            path: /mnt/tank/server/media
