apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
commonLabels:
  app: vaultwarden
resources:
  - middleware.redirect-to-https.yaml
  - persistent-volume-claim.yaml
configMapGenerator:
  - name: arr-common-config
    literals:
      - PGID=1000
      - PUID=1000
      - TZ=Asia/Tokyo
