apiVersion: v1
kind: Pod
metadata:
  name: media-migration
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command: ["sh", "-c", "while true; do sleep 3600; done"]
      volumeMounts:
        # Longhorn volumes
        - name: bazarr-config
          mountPath: /a/old/bazarr
        - name: jellyfin-config
          mountPath: /a/old/jellyfin
        - name: lidarr-config
          mountPath: /a/old/lidarr
        - name: prowlarr-config
          mountPath: /a/old/prowlarr
        - name: radarr-config
          mountPath: /a/old/radarr
        - name: sonarr-config
          mountPath: /a/old/sonarr
        - name: transmission-config
          mountPath: /a/old/transmission
        - name: media-data
          mountPath: /a/old/media-data

        # New NFS destination
        - name: media-new
          mountPath: /a/new
  volumes:
    # Longhorn volumes
    - name: bazarr-config
      persistentVolumeClaim:
        claimName: bazarr-config
    - name: jellyfin-config
      persistentVolumeClaim:
        claimName: jellyfin-config
    - name: lidarr-config
      persistentVolumeClaim:
        claimName: lidarr-config
    - name: prowlarr-config
      persistentVolumeClaim:
        claimName: prowlarr-config
    - name: radarr-config
      persistentVolumeClaim:
        claimName: radarr-config
    - name: sonarr-config
      persistentVolumeClaim:
        claimName: sonarr-config
    - name: transmission-config
      persistentVolumeClaim:
        claimName: transmission-config
    - name: media-data
      persistentVolumeClaim:
        claimName: media-data

    # New NFS
    - name: media-new
      nfs:
        server: hactar.lan
        path: /mnt/tank/server/media
