apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: jellyfin
          image: linuxserver/jellyfin:10.8.10
          envFrom:
            - configMapRef:
                name: arr-common-config
          env:
            - name: JELLYFIN_PublishedServerUrl
              value: jellyfin.lan
          ports:
            - name: http
              containerPort: 8096
            - containerPort: 8920
            - containerPort: 7359
              protocol: UDP
            - containerPort: 1900
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: config
          nfs:
            server: hactar.lan
            path: /mnt/tank/server/media/jellyfin
        - name: data
          nfs:
            server: hactar.lan
            path: /mnt/tank/server/media/data
