apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich
spec:
  selector:
    matchLabels:
      app: immich
  template:
    metadata:
      labels:
        app: immich
    spec:
      containers:
        - name: server
          image: ghcr.io/immich-app/immich-server:v1.123.0
          ports:
            - name: http
              containerPort: 2283
          env:
            - name: DB_HOSTNAME
              value: immich-db
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: immich.immich-db.credentials.postgresql.acid.zalan.do
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich.immich-db.credentials.postgresql.acid.zalan.do
                  key: password
            - name: DB_DATABASE_NAME
              value: immich
            - name: IMMICH_PORT
              value: "2283"
            - name: REDIS_HOSTNAME
              value: immich-cache
            - name: TZ
              value: Asia/Tokyo
          volumeMounts:
            - name: immich-data
              mountPath: /usr/src/app/upload
              subPath: data
      volumes:
        - name: immich-data
          nfs:
            server: hactar.lan
            path: /mnt/tank/server/immich
