apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-ml
spec:
  selector:
    matchLabels:
      app: immich-ml
  replicas: 1
  template:
    metadata:
      labels:
        app: immich-ml
    spec:
      containers:
        - name: server
          image: ghcr.io/immich-app/immich-machine-learning:v1.123.0
          ports:
            - name: http
              containerPort: 3003
          env:
            - name: IMMICH_PORT
              value: "3003"
          volumeMounts:
            - name: immich-ml-data
              mountPath: /cache
      volumes:
        - name: immich-ml-data
          nfs:
            server: hactar.lan
            path: /mnt/tank/server/immich/ml
