apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-postgres-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: hactar.lan
    path: /mnt/tank/server/immich/db
