apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-cache
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: hactar.lan
    path: /mnt/tank/server/immich/cache
---
apiVersion: v1
kind: Service
metadata:
  name: immich-cache
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
