apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
commonLabels:
  app: plex
resources:
  - deployment.yaml
  - ingress.http.yaml
  - ingress.https.yaml
  - persistent-volume-claim.yaml
  - service.yaml
