apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: fook
spec:
  allowScheduling: false
  disks: {}
  engineManagerCPURequest: 0
  evictionRequested: false
  name: fook
  replicaManagerCPURequest: 0
  tags: []
