apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: fook
spec:
  allowScheduling: false
  disks:
    default-disk-524aac100a76cc85:
      allowScheduling: false
      evictionRequested: false
      path: /var/lib/longhorn/
      storageReserved: 9186888499
      tags: []
  engineManagerCPURequest: 0
  evictionRequested: false
  name: fook
  replicaManagerCPURequest: 0
  tags: []
