apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  # - frankie.yaml
  # - benjy.yaml
  # - lunkwill.yaml
  - fook.yaml
# patches:
#   - path: fook.remove-disk.json
#     target:
#       group: longhorn.io
#       version: v1beta2
#       kind: Node
#       name: fook
