apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonLabels:
  app: dyndns
resources:
  - cron-job.yaml
  - sealed-secret.dyndns-settings.yaml
configMapGenerator:
  - name: dyndns-updater
    files:
      - resources/dyndns-updater.sh
