apiVersion: batch/v1
kind: CronJob
metadata:
  name: cat-referral
spec:
  schedule: "* * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: gluetun
              image: qmcgaw/gluetun:latest
              imagePullPolicy: Always
              securityContext:
                capabilities:
                  add:
                    - NET_ADMIN
              ports:
                - containerPort: 9091
              env:
                - name: TZ
                  value: Asia/Tokyo
                - name: VPN_SERVICE_PROVIDER
                  value: private internet access
              envFrom:
                - secretRef:
                    name: pia-credentials
            - name: cat-referral
              image: curlimages/curl:8.9.1
              command:
                - "/bin/sh"
                - "/app/cat-referral.sh"
              volumeMounts:
                - name: cat-referral
                  mountPath: /app/cat-referral.sh
                  subPath: cat-referral.sh
                  readOnly: true
          restartPolicy: Never
          volumes:
            - name: cat-referral
              projected:
                defaultMode: 0755
                sources:
                  - configMap:
                      name: cat-referral
                      items:
                        - key: cat-referral.sh
                          path: cat-referral.sh
