apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/CrunchyData/postgres-operator-examples/kustomize/install/namespace
  - github.com/CrunchyData/postgres-operator-examples/kustomize/install/default
