apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-operator
resources:
  - github.com/zalando/postgres-operator/manifests
images:
  - name: registry.opensource.zalan.do/acid/postgres-operator
    newName: ghcr.io/zalando/postgres-operator
