apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: web
    spec:
      containers:
        - name: ghost
          image: ghost@sha256:4540063588cbabc52c752b7a8571da17e68f6736db34671801cbb7922228b895
          envFrom:
            - configMapRef:
                name: ghost-config
            - secretRef:
                name: smtp-password
          env:
            - name: database__connection__user
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: user-username
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: user-password
          ports:
            - name: http
              containerPort: 2368
          volumeMounts:
            - name: data
              mountPath: /var/lib/ghost/content
      volumes:
        - name: data
          nfs:
            server: hactar.lan
            path: /mnt/tank/server/blog/data
