apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1
  template:
    spec:
      metadata:
        labels:
          role: web
      containers:
        - name: ghost
          image: ghost:5.49.3-alpine
          envFrom:
            configMapRef:
              name: ghost-config
          env:
            - name: database__connection__user
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: user-username
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: user-password
          ports:
            - name: http
              containerPort: 2368
          volumeMounts:
            - name: data
              mountPath: /var/lib/ghost/content
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ghost-data
