apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog
commonLabels:
  app: blog
resources:
  - config-map.ghost.yaml
  - deployment.ghost.yaml
  - deployment.mysql.yaml
  - ingress.http.yaml
  - ingress.https.yaml
  - middleware.redirect-to-https.yaml
  - persistent-volume-claim.ghost-data.yaml
  - persistent-volume-claim.mysql-data.yaml
  - sealed-secret.mysql-credentials.yaml
  - service.ghost.yaml
  - service.mysql.yaml
