apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: smtp-password
  namespace: blog
spec:
  encryptedData:
    mail__options__auth__pass: AgBWLT7i34BjwACy+GunrOTvFcJA4cA4WFt6JPNfTX1m6FGSmJs/4IxUV5LsVjCZC9oKLLWyCKuOYOnIgPMwTd5avz2Vr43vLuLUL+j+Z/DQnABUljkv+AwZ1KUQcawtQ3Q/seDpZzrYRXqBlHoh4c5xp6nse539YWgpJ/vWK7g/nv0A/Uv4xkpboo9xJr8MxW5IeE61V+/hT5dkSy161RhWT0GGrQmHKefJazZkpMRgrGW0fzrtU8AA+fXbFkbwL8QC0eGk+iVUak+pyrysb/7jg8wvwYrVzHM/0yrTCsFoE+MtXdbdL0eB6sRWXEYJ9+Tqd6bcSHJkBOBSaf82Lgg1NfqFd9GkVogzsahLYbSF13WPT2BYbkG8EA45PrZUVzks0vUV/cy0DZWcF0vRfW4cpDzCuhUSPtK64oHYx/fMbg6JSdhtQ9OG850GwTPQgEpdSGu2mmA+7iwG+ImqOOxDZ788pdt5ckWt467Zpw8dQe7jP3xce42xyWQB+FMVXYHmOJIRofxVdeXCFKQX/cF/tEVGOkx5uU747Le4ps12OarQ/M/bZ9f9mh4m1XwfuANbHANak94g3hC7nWBRjDMJ+49QaP8lZHK5WJNLxxikDF0zB5cC2z+kZPGStY2C5JIM7XlVmvf2c5HKq4QEF0Kq9/hrj/eCGyYKhq1+V1JTCXTsSGwlASBA66mf8VH70VuHlpBpJpqAMD0RIdU6nmQF
  template:
    metadata:
      creationTimestamp: null
      name: smtp-password
      namespace: blog

