apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/v0.12.2/manifests/install.yaml
  - application.yaml
  - applications/
  - certificate.yaml
  - ingress-route.http.yaml
  - ingress-route.https.yaml
  - middleware.redirect-to-https.yaml
patches:
  - path: config-map.argocd-cmd-params-cm.yaml
  # - path: config-map.argocd-image-updater-config.yaml
  - path: deployment.argocd-image-updater.yaml
