apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflared
commonLabels:
  app: cloudflared
resources:
  - config-map.yaml
  - deployment.yaml
  # - sealed-secret.tunnel-credentials.yaml
