apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflared
commonLabels:
  app: cloudflared
resources:
- deployment.yaml
- sealed-secret.tunnel-credentials.yaml
configMapGenerator:
- name: cloudflared-config
  files:
  - resources/config.yaml
images:
- name: cloudflare/cloudflared
  newTag: 2024.10.1
