apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: atlantis
spec:
  encryptedData:
    credentials.json: AgAhxJgZppdqSVGYt5ksWN4doxs9LlaEtKfsX9S7W+xOhm0nqAarWy1k2VkNE4EwLTDdeBfUED/AC8gPQ1D8OVNeql1iAKmnmWvQ48ruxeL/vRx2O4IO2fQ/eYqg/NIKyyTSt9Sa/zJG0uhHlJ8V+zxrnwEQx18+rxdBwWRA/pKCnir7LwXBtjpyHiKP5ofhmZW72HhzflC6IiKDeoTtNemKNXJ1BN+2BrlIXus3zI0G59hghrGjfQaanFbRynMy7Rui7u5yXIPoB9xURjd0ehtsOCW8J+1+z0pWEl34DxBv6iZypvZtUCKnXinRphPRRRWsS9oftI7VdtprtUG2QcwUfMd5PwCfIjwd8wXWXBH3AwtVncOGXnT1J4HekhySEVL2sxlA/5AWd/Emv05i9xSkcpZNNzY6ulx+LH1xT4GQ3ZL6UkKKW23tjmxAY9rtzNOTtfL1sSXiuBRdcbyO9QbsFOTPh0ddXLwn7PL/PdWvWBc2tIFaMcRLHgS/DgBw0c8EfbQNxG9U9URv9tV+24+2ptxg0mDeDeDQCtBBPTSMHRE41UjnVTgxVOqPBeI9RLmkA/g6gIX2z7OnPtKa0tepSj2xqDENpWw9gKci3rVNWgfUV4pt8d2yxFPPSmkpyB2nVz85BZ85fpXH5TmHEzSEP/jQfS1/fR0StG595Z3lfs6NGqQjUIfRtcS9Q44eBxrwHmQrYnQGbBsf+Ym87PN/QkvMa4Fan6tIFT3rEmlKO4K2HvFd9cASWl864Fb/ovU7tzg7kNUaboAybI84Q9zednUVc6IdX0oIWlQemw6AamZXxaoE/JQUgHO05sUX1CfM/+MI1n7Chk0DRmQnVLB8h9wrgK4n2A9zOpa++1NYKz5cCewswOQ1RNTapUEpsWj47AsEgjJ0LBnP9xthsqZ5gA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: atlantis

