apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAE5EsuiIxoLqjAqLWvPOCTFX/EM+9NgaNfAAqRF03f1zGY/rpjCTwyShf9Lecvdcgr1hi5yLQSLaXW3BOL+shumd0airMMWUGE/Y2Ew3EjO1lKuLHjrqJdD2pBrWdEfrcwJpNpJFyDxH4Yp2ggbVXfXGJ/l6ZssYcth9+UjP+0LI680Iyhy3i7t5Y/e0SSXOW+uVfjmvAr9Bj4g5D38+QCKfXsSkwe47koAdW+vtm3KvsLVtiK/PsUGXSgsKsLWpTJBDo9+7SJiW+QZmRYVQBmhHaE1WV484UllsyCKtpEAPHMKMIOQ9KmxzB+jVQS6wX/JYDl6siol8R63xA/DTGrAQM7mKkUwfEevNfGo6Jw4S5+ZTAIA4ew/VWXqOjnu0TStgR3VQFhamMijDYMtV1hpewswgHv+RK4nYZikahWY0y78EHaBddoZGUdGPfpfm5Ki6/ek/68Bfe7X0SrkGPFsjK2RwG5YO3lQyKRqijFk9BKRuylXxeCDEv8SYS4YuhJDuPrK44N6eTvGZlMjxEYNh6v2bTymF1bTgFfDTzWsIsSrSQv8Od+WGFaKlOnoLMGB8VgdUqf25C81M337xlFXv4XEw26xIWIhu40A9/IXHY+a8zZ5fpnk/UTB3C2U40+YYyKG9BcFD0HWZvpznvuoiJMMVmRQcVjV2XduHY0W7tNFbXMhKTUM9KbwNJagYwYW7h+N9d+svTMP2Jkf5FUpOjFa943KEOhI51s0f7oO4uhryvubaBaKdQsMWDom22v4Iz9ZK/+d1rjOzTa5d9j4LkMDfcaE30qHeXFPKLu1L9VhK7hJdpVB5tmnzF2Z8uZXwnzi8ItWdwk4cLe0qN4adhE/QK39S7e/CRvahhqGMSZRsr67z95ki4r93uobqROPIkygZ6jl5KfQ7KOhUUd0g==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared

