apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
spec:
  replicas: 0
  template:
    spec:
      containers:
        - name: transmission
          image: haugene/transmission-openvpn:5.0.2
          envFrom:
            - configMapRef:
                name: transmission-config
            - secretRef:
                name: pia-credentials
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - name: http
              containerPort: 9091
          volumeMounts:
            - name: media
              mountPath: /config
              subPath: transmission
            - name: media
              mountPath: /data
              subPath: library
      volumes:
        - name: media
          nfs:
            server: hactar.lan
            path: /mnt/tank/server/media
