
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
commonLabels:
  app: transmission
resources:
  - config-map.yaml
  - deployment.yaml
  - ingress.http.yaml
  - ingress.https.yaml
  - persistent-volume-claim.yaml
  - sealed-secret.yaml
  - service.yaml
