apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Cellane/homelab.git
    targetRevision: master
    path: atlantis
  destination:
    server: https://kubernetes.default.svc
    namespace: atlantis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
