apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dyndns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Cellane/homelab.git
    targetRevision: master
    path: dyndns
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
