apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/image-list: sonarr=linuxserver/sonarr
    argocd-image-updater.argoproj.io/sonarr.update-strategy: name
    argocd-image-updater.argoproj.io/sonarr.allow-tags: regexp:^develop-4(\.\d+)+-ls\d+$
spec:
  project: default
  source:
    repoURL: git@github.com:Cellane/homelab.git
    targetRevision: master
    path: media
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
