apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/image-list: bazarr=linuxserver/bazarr:latest, jellyfin=linuxserver/jellyfin:10.x, lidarr=linuxserver/lidarr:develop, prowlarr=linuxserever/prowlarr:develop radarr=linuxserver/radarr:develop, sonarr=linuxserver/sonarr:develop, transmission=haugene/transmission:5.x
    argocd-image-updater.argoproj.io/bazarr.update-strategy: digest
    argocd-image-updater.argoproj.io/jellyfin.allow-tags: regexp:^10\..*$
    argocd-image-updater.argoproj.io/jellyfin.update-strategy: semver
    argocd-image-updater.argoproj.io/lidarr.update-strategy: digest
    argocd-image-updater.argoproj.io/prowlarr.update-strategy: digest
    argocd-image-updater.argoproj.io/radarr.update-strategy: digest
    argocd-image-updater.argoproj.io/sonarr.update-strategy: digest
    argocd-image-updater.argoproj.io/transmission.allow-tags: regexp:^5\..*$
    argocd-image-updater.argoproj.io/transmission.update-strategy: semver
spec:
  project: default
  source:
    repoURL: git@github.com:Cellane/homelab.git
    targetRevision: master
    path: media
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
