apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/image-list: influxdb=influxdb:2.x,grafana=grafana/grafana:12.x
    argocd-image-updater.argoproj.io/influxdb.allow-tags: "regexp:^[0-9]+\\.[0-9]+\\.[0-9]+$"
    argocd-image-updater.argoproj.io/grafana.allow-tags: "regexp:^[0-9]+\\.[0-9]+\\.[0-9]+$"
spec:
  project: default
  source:
    repoURL: git@github.com:Cellane/homelab.git
    targetRevision: master
    path: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
