apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: lidarr
          image: linuxserver/lidarr:1.2.0-develop
          envFrom:
            - configMapRef:
                name: arr-common-config
          ports:
            - name: http
              containerPort: 8686
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: lidarr-config
        - name: data
          persistentVolumeClaim:
            claimName: media-data
