apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
spec:
  replicas: 0
  template:
    spec:
      containers:
        - name: lidarr
          image: linuxserver/lidarr@sha256:e9f86b7fa0ecddca3ea92359ff02fa6d0dc535cdcabcddccf20e1af79d0eaea1
          envFrom:
            - configMapRef:
                name: arr-common-config
          ports:
            - name: http
              containerPort: 8686
          volumeMounts:
            - name: media
              mountPath: /config
              subPath: lidarr
            - name: media
              mountPath: /data
              subPath: library
      volumes:
        - name: media
          nfs:
            server: hactar.lan
            path: /mnt/tank/server/media
