apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - sealed-secret.pihole-password.yaml
  - deployment.yaml
