apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-password
  namespace: default
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgCqJf9t92/OIG9jK/jIbOGW7/j8+0uFV1f4azlsiFRDZvvUwrvj3HdpxKWVHgymaT2yzZMXUbxsZxkA8BqdsAuFXgMlUcJKK/1h25SJ2rFrn6JoB8CDARAh0A6njTIQ2dQbO13wov3JcEqbviKXGX5nhIOlhZpfL1SUk2F08Tgm6oBXqbg3n4jZJFEsuJ/QPReiZ+IaNjtGoOETT/Ms2a5xdLFTVE3u7OxQV1pi37tpzb9bAvdoqzKP8rJnOlSIN15r0q+LgxcYLZ022AAVYtzm0VGje1FSIG0X/eO63Ats7F1dj8XDUbYUdcs8Acjw5rxvjrYrz11nAW080sAfrXz/6DxHaNx1U1RHIaZG3Yh/53YcsVc4t2m1CmJnIxMOV9KnsySa1hb8zp67kfEl4Pn+cVo7eJVXNLj2n0qNiuZYgJ89J2cycz3HpVlbk5zcrvshDK8HACnF1ztm4urNim5z0B6Jr4SZO8i62ValDMsnGM0TXk5Y3VffIVijqdD9WTlbErDrZCoURBLrTwxFmANoW4jrpFmETWxTz5fJDqpkXulgs2qew0LjdKj/htnvVT16SbUG0N9BZZLh57a7kdDdYxdYr8D2numxcOJRmWwvgoOq+3K2RPq1x3wL7Ppjg7ITNV2H5ACIaRevlcomdwIDWyND4WnZeJaO+w7LzUHTfIoMi468RXnvgyTj014cmjU+kK65cvEzPuX7ykOMIcP2
  template:
    metadata:
      creationTimestamp: null
      name: pihole-password
      namespace: default

