apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
spec:
  replicas: 0
  template:
    spec:
      containers:
        - name: bazarr
          image: linuxserver/bazarr@sha256:3dda85b4539181ec8ab3c588b948e84599324635e477830b4dc75cf78bee14f7
          envFrom:
            - configMapRef:
                name: arr-common-config
          ports:
            - name: http
              containerPort: 6767
          volumeMounts:
            - name: media
              mountPath: /config
              subPath: bazarr
            - name: media
              mountPath: /data
              subPath: library
      volumes:
        - name: media
          nfs:
            server: hactar.lan
            path: /mnt/tank/server/media
