apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: bazarr
          image: linuxserver/bazarr:1.2.1
          envFrom:
            - configMapRef:
                name: arr-common-config
          ports:
            - name: http
              containerPort: 6767
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: bazarr-config
        - name: data
          persistentVolumeClaim:
            claimName: media-data
