apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: repo-config
data:
  repo_config.json: |
    {
      "workflows": {
        "default": {
          "plan": {
            "steps": [
              {
                "run": "terraform init -input=false -no-color"
              },
              {
                "run": "terraform plan -input=false -no-color"
              }
            ]
          },
          "apply": {
            "steps": [
              {
                "run": "terraform apply -auto-approve -input=false -no-color"
              }
            ]
          }
        }
      },
      "repos": [
        {
          "id": "/.*/",
          "allowed_overrides": [
            "workflow"
          ],
          "allow_custom_workflows": true
        }
      ]
    }
