apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: atlantis
commonLabels:
  app: atlantis
resources:
  - github.com/runatlantis/atlantis//kustomize
  - persistent-volume-claim.yaml
  - sealed-secret.atlantis-vcs.yaml
patches:
- patch: |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: atlantis
    spec:
      template:
        spec:
          containers:
            - name: atlantis
              env:
                - name: ATLANTIS_REPO_ALLOWLIST
                  value: github.com/Cellane/*
                - name: ATLANTIS_GH_USER
                  value: Voilane
                - name: ATLANTIS_GH_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: atlantis-vcs
                      key: token
                - name: ATLANTIS_GH_WEBHOOK_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: atlantis-vcs
                      key: webhook-secret
