apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: atlantis
commonLabels:
  app: atlantis
resources:
  - github.com/runatlantis/atlantis//kustomize
  - persistent-volume-claim.yaml
  - sealed-secret.atlantis-vcs.yaml
patches:
  - patch: stateful-set.atlantis.yaml
