apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: atlantis
resources:
  - github.com/runatlantis/atlantis//kustomize
  - ingress.http.yaml
  - ingress.https.yaml
  - middleware.redirect-to-https.yaml
  - migration.yaml
  - sealed-secret.atlantis-tfe.yaml
  - sealed-secret.atlantis-vcs.yaml
patches:
  - path: stateful-set.atlantis.yaml
configMapGenerator:
  - files:
    - resources/repo_config.json
    name: repo-config
labels:
  - includeSelectors: true
    pairs:
      app: atlantis
