apiVersion: v1
kind: Pod  # Use Pod instead of Deployment since it's temporary
metadata:
  name: migration-helper
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: old
      mountPath: /old
    - name: new
      mountPath: /new
  volumes:
  - name: old
    persistentVolumeClaim:
      claimName: atlantis-data-atlantis-0
  - name: new
    nfs:
      server: hactar.lan
      path: /mnt/tank/server/atlantis
