apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atlantis
spec:
  replicas: 0
  template:
    spec:
      containers:
        - name: atlantis
          env:
            - name: ATLANTIS_REPO_ALLOWLIST
              value: github.com/Cellane/*
            - name: ATLANTIS_GH_USER
              value: Voilane
            - name: ATLANTIS_REPO_CONFIG_JSON
              valueFrom:
                configMapKeyRef:
                  name: repo-config
                  key: repo_config.json
            - name: ATLANTIS_GH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: atlantis-vcs
                  key: token
            - name: ATLANTIS_GH_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: atlantis-vcs
                  key: webhook-secret
            - name: ATLANTIS_TFE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: atlantis-tfe
                  key: token
          volumes:
            - name: atlantis-data
              nfs:
                server: hactar.lan
                mountPath: /mnt/tank/server/atlantis
---
kind: Pod  # Use Pod instead of Deployment since it's temporary
metadata:
  name: migration-helper
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: old
      mountPath: /old
    - name: new
      mountPath: /new
  volumes:
  - name: old
    persistentVolumeClaim:
      claimName: atlantis-data-atlantis-0
  - name: new
    nfs:
      server: hactar.lan
      path: /mnt/tank/server/atlantis
