apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atlantis
spec:
  replicas: 0
  template:
    spec:
      containers:
        - name: atlantis
          env:
            - name: ATLANTIS_REPO_ALLOWLIST
              value: github.com/Cellane/*
            - name: ATLANTIS_GH_USER
              value: Voilane
            - name: ATLANTIS_REPO_CONFIG_JSON
              valueFrom:
                configMapKeyRef:
                  name: repo-config
                  key: repo_config.json
            - name: ATLANTIS_GH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: atlantis-vcs
                  key: token
            - name: ATLANTIS_GH_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: atlantis-vcs
                  key: webhook-secret
            - name: ATLANTIS_TFE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: atlantis-tfe
                  key: token
          volumes:
            - name: atlantis-data
              nfs:
                server: hactar.lan
                mountPath: /mnt/tank/server/atlantis
