apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Omit namespace as the manifest installs things to multiple namespaces
# namespace: cert-manager
resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml
  - clusterissuer.yaml
  - certificate.yaml
  - issuer.yaml
