apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
provisioner: kubernetes.io/no-provisioner  # Static provisioning
volumeBindingMode: WaitForFirstConsumer    # Wait for pod to be scheduled
